version: '3.8'

services:

  postgres:
    image: singhalmradul/high-five/postgres:0.0.1-SNAPSHOT
    ports:
      - 5432:5432
    networks:
      - high-five-network

  naming-server:
    image: singhalmradul/high-five_naming-server:0.0.1-SNAPSHOT
    mem_limit: 768m
    ports:
      - 8761:8761
    networks:
      - high-five-network

  gateway:
    image: singhalmradul/high-five_gateway:0.0.1-SNAPSHOT
    mem_limit: 768m
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    networks:
      - high-five-network

  post-service:
    image: singhalmradul/high-five_post-service:0.0.1-SNAPSHOT
    mem_limit: 768m
    ports:
      - 11111:11111
    depends_on:
      - postgres
      - naming-server
      - user-service
    networks:
      - high-five-network

  user-service:
    image: singhalmradul/high-five_user-service:0.0.1-SNAPSHOT
    mem_limit: 768m
    ports:
      - 22222:22222
    depends_on:
      - postgres
      - naming-server
    networks:
      - high-five-network

  # frontend:
  #   image: singhalmradul/high-five-frontend:0.0.1-SNAPSHOT
  #   mem_limit: 768m
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - REACT_APP_BACKEND_URL=http://gateway:8765
  #   depends_on:
  #     - gateway
  #     - post-service
  #   networks:
  #     - high-five-network

networks:
  high-five-network:
