version: '3.8'

services:
  high-five:
    container_name: high-five
    image: high-five:0.1.0
    working_dir: /usr/src/high-five
    volumes:
      - ./:/ursr/src/high-five
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'
  postgres:
    container_name: postgres
    image: postgres:16.0-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: high-five
    ports:
      - '5432:5432'
