version: '3.8'

services:

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=high-five
    ports:
      - 5432:5432

  naming-server:
    image: singhalmradul/high-five_naming-server:0.0.1-SNAPSHOT
    mem_limit: 768m
    ports:
      - 8761:8761

  gateway:
    image: singhalmradul/high-five_gateway:0.0.1-SNAPSHOT
    mem_limit: 768m
    ports:
      - 8765:8765
    depends_on:
      - naming-server

  post-service:
    image: singhalmradul/high-five_posts-service:0.0.1-SNAPSHOT
    mem_limit: 768m
    ports:
      - 11111:11111
    depends_on:
      - postgres
      - naming-server