services:

  db-9000_01:
    build: high-five_db/db-9000_01
    image: singhalmradul/high-five_db-9000_01:0.1.0
    mem_limit: 256m
    ports:
      - 5432:5432
    networks:
      - high-five-network
    restart: on-failure

  db-9000_02:
    build: high-five_db/db-9000_02
    image: singhalmradul/high-five_db-9000_02:0.1.0
    mem_limit: 256m
    ports:
      - 5433:5432
    networks:
      - high-five-network
    restart: on-failure

  db-9000_03-22222_01:
    build: high-five_db/db-9000_03-22222_01
    image: singhalmradul/high-five_db-9000_03-22222_01:0.1.0
    mem_limit: 256m
    ports:
      - 5434:5432
    networks:
      - high-five-network
    restart: on-failure

  db-11111_01:
    build: high-five_db/db-11111_01
    image: singhalmradul/high-five_db-11111_01:0.1.0
    mem_limit: 256m
    ports:
      - 27018:27017
    networks:
      - high-five-network
    restart: on-failure

  db-14641_01:
    build: high-five_db/db-14641_01
    image: singhalmradul/high-five_db-14641_01:0.1.0
    mem_limit: 256m
    ports:
      - 27019:27017
    networks:
      - high-five-network
    restart: on-failure

  db-22222_02:
    build: high-five_db/db-22222_02
    image: singhalmradul/high-five_db-22222_02:0.1.0
    mem_limit: 256m
    ports:
      - 27017:27017
    networks:
      - high-five-network
    restart: on-failure

  db-33333_01:
    build: high-five_db/db-33333_01
    image: singhalmradul/high-five_db-33333_01:0.1.0
    mem_limit: 512m
    ports:
      - 9042:9042
    networks:
      - high-five-network
    restart: on-failure

  db-44444-01:
    build: high-five_db/db-44444_01
    image: singhalmradul/high-five_db-44444_01:0.1.0
    mem_limit: 512m
    ports:
      - 7687:7687
    networks:
      - high-five-network
    restart: on-failure

  primary-reverse-proxy:
    build: high-five_primary-reverse-proxy
    image: singhalmradul/high-five_primary-reverse-proxy:0.1.0
    mem_limit: 768m
    ports:
      - 8080:80
    depends_on:
      - authorisation-server
      - reverse-proxy
    networks:
      - high-five-network
    restart: on-failure

  service-registry:
    image: singhalmradul/high-five_service-registry:0.1.0
    mem_limit: 768m
    ports:
      - 8761:8761
    networks:
      - high-five-network
    restart: on-failure

  authorisation-server:
    image: singhalmradul/high-five_authorization-server:0.1.0
    mem_limit: 768m
    ports:
      - 9000:9000
    depends_on:
      - db-9000_01
      - db-9000_02
      - db-9000_03-22222_01
      - service-registry
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka
      - DB_1_URL=jdbc:postgresql://db-9000_01:5432/high-five
      - DB_1_USERNAME=postgres
      - DB_1_PASSWORD=postgres
      - DB_2_URL=jdbc:postgresql://db-9000_02:5432/high-five
      - DB_2_USERNAME=postgres
      - DB_2_PASSWORD=postgres
      - DB_3_URL=jdbc:postgresql://db-9000_03-22222_01:5432/high-five
      - DB_3_USERNAME=postgres
      - DB_3_PASSWORD=postgres
    networks:
      - high-five-network
    restart: on-failure

  reverse-proxy:
    image: singhalmradul/high-five_reverse-proxy:0.1.0
    mem_limit: 768m
    ports:
      - 8765:8765
    depends_on:
      - service-registry
      - authorisation-server
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka
      - AUTHORIZATION_SERVER_URI=http://authorisation-server:9000
    networks:
      - high-five-network
    restart: on-failure

  post-service:
    image: singhalmradul/high-five_post-service:0.1.0
    mem_limit: 768m
    ports:
      - 11111:11111
    depends_on:
      - db-11111_01
      - service-registry
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka
      - DB_URI=mongodb://db-11111_01:27017/high-five
      - CLOUDINARY_URL=${CLOUDINARY_URL}
    networks:
      - high-five-network
    restart: on-failure

  comment-service:
    image: singhalmradul/high-five_comment-service:0.1.0
    mem_limit: 768m
    ports:
      - 14641:14641
    depends_on:
      - db-14641_01
      - service-registry
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka
      - DB_URI=mongodb://db-14641_01:27017/high-five
      - CLOUDINARY_URL=${CLOUDINARY_URL}
    networks:
      - high-five-network
    restart: on-failure

  follow-service:
    image: singhalmradul/high-five_follow-service:0.1.0
    mem_limit: 768m
    ports:
      - 44444:44444
    depends_on:
      - db-44444-01
      - service-registry
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka
      - NEO4J_URI=bolt://db-44444-01:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=high-five
    networks:
      - high-five-network
    restart: on-failure

  like-service:
    image: singhalmradul/high-five_like-service:0.1.0
    mem_limit: 768m
    ports:
      - 33333:33333
    depends_on:
      - db-33333_01
      - service-registry
      - user-service
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka
      - CASSANDRA_CONTACTPOINTS=db-33333_01
      - CASSANDRA_PORT=9042
    networks:
      - high-five-network
    restart: on-failure

  user-service:
    image: singhalmradul/high-five_user-service:0.1.0
    mem_limit: 768m
    ports:
    - 22222:22222
    depends_on:
      - db-9000_03-22222_01
      - db-22222_02
      - service-registry
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka
      - DB_1_URL=jdbc:postgresql://db-9000_03-22222_01:5432/high-five
      - DB_1_USERNAME=postgres
      - DB_1_PASSWORD=postgres
      - DB_2_URI=mongodb://db-22222_02:27017/high-five
    networks:
      - high-five-network
    restart: on-failure

networks:
  high-five-network: