spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/high-five
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true
